<?php
	function reconstruct_speculations($speculations){
		$html_speculations = "";
		foreach($speculations as $speculation){
						$html_speculations .=
			"<div class='base'>"
				."<!-- Champ speculation id -->"
				."<input type='hidden' id='speculation_id' name='speculation_id[]' value='".$speculation['id']."'/>"     

				."<!--  Speculation -->"																
				."<div class='form-group pb-0 pt-0 mt-0'>"
					."<label for='speculation' class='font-weight-bold'>Sp&eacute;culation</label>"
					."<select required class='form-control' id='speculation' name='speculation[]'>"
						."<option value='GOMBO' ".(($speculation['speculation'] == 'GOMBO')? 'selected' : '').">Gombo</option>"
						."<option value='TOMATE' ".(($speculation['speculation'] == 'TOMATE')? 'selected' : '').">Tomate</option>"
						."<option value='OIGNON' ".(($speculation['speculation'] == 'OIGNON')? 'selected' : '').">Oignon</option>"
						."<option value='AUBERGINE' ".(($speculation['speculation'] == 'AUBERGINE')? 'selected' : '').">Aubergine</option>"
						."<option value='POIVRON' ".(($speculation['speculation'] == 'POIVRON')? 'selected' : '').">Poivron</option>"
						."<option value='PIMENT' ".(($speculation['speculation'] == 'PIMENT')? 'selected' : '').">Piment</option>"
						."<option value='RIZ' ".(($speculation['speculation'] == 'RIZ')? 'selected' : '').">Riz</option>"
						."<option value='PASTEQUE' ".(($speculation['speculation'] == 'PASTEQUE')? 'selected' : '').">Past&egrave;que</option>"
						."<option value='AUTRE' ".(($speculation['speculation'] == 'AUTRE')? 'selected' : '').">Autre</option>"
					."</select>"
				."</div>"
				."<!-- surperficie emblavee -->"
				."<div class='form-group pb-0 pt-0 mt-0'>"
					."<label for='planted_area' class='font-weight-bold'>Superficie emblav&eacute;e</label>"
					."<input data-validation='number required' data-validation-allowing='float'  class='form-control'  id='planted_area' name='planted_area[]' placeholder='en ha' value='".$speculation['planted_area']."'/>"       
				."</div>"
				."<!-- Date de debut / fin de la recolte  -->"
				."<label for='' class='font-weight-bold'>Date d&eacute;but / fin r&eacute;colte</label>"									
				."<div class='form-row pb-0 pt-0 mt-0 mb-3'>"
					."<div class='col'>"
						."<label for='harvest_start_date' class='font-weight-bold text-muted'>D&eacute;but</label>"
						."<input required class='form-control' type='date' id='harvest_start_date' name='harvest_start_date[]' value='".$speculation['harvest_start_date']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='harvest_end_date_1' class='font-weight-bold text-muted'>Fin</label>"
						."<input required class='form-control' type='date' id='harvest_end_date_1' name='harvest_end_date_1[]' value='".$speculation['harvest_end_date_1']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='harvest_end_date_2' class='font-weight-bold text-muted'>Fin</label>"
						."<input class='form-control' type='date' id='harvest_end_date_2' name='harvest_end_date_2[]' value='".$speculation['harvest_end_date_2']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='harvest_end_date_3' class='font-weight-bold text-muted'>Fin</label>"
						."<input class='form-control' type='date' id='harvest_end_date_3' name='harvest_end_date_3[]' value='".$speculation['harvest_end_date_3']."'/>"       
					."</div>"
				."</div>"	
				."<!-- Quantite recolte -->"
				."<div class='form-group pb-0 pt-0 mt-0'>"
					."<label for='harvest_quantity' class='font-weight-bold'>Quantite r&eacute;colt&eacute;e</label>"
					."<input required class='form-control' type='number' id='harvest_quantity' name='harvest_quantity[]' value='".$speculation['harvest_quantity']."'/>"       
				."</div>"		
				."<!-- QUantite vendue Sans / Sous Contrat  -->"
				."<label for='' class='font-weight-bold'>Quantit&eacute; vendue</label>	"								
				."<div class='form-row pb-0 pt-0 mt-0 mb-3'>"
					."<div class='col'>"
						."<label for='quantity_selled_with_contract' class='font-weight-bold text-muted'>Sous contrat</label>"
						."<input required class='form-control' type='number' id='quantity_selled_with_contract' name='quantity_selled_with_contract[]' value='".$speculation['quantity_selled_with_contract']."'/>  "     
					."</div>"
					."<div class='col'>"
						."<label for='quantity_selled_without_contract' class='font-weight-bold text-muted'>Hors contrat</label>"
						."<input required class='form-control' type='number' id='quantity_selled_without_contract' name='quantity_selled_without_contract[]' value='".$speculation['quantity_selled_without_contract']."'/>"       
					."</div>"
				."</div>"
				."<!-- Montant vente Sans / Sous Contrat  -->"
				."<label for='' class='font-weight-bold'>Montant vente</label>	"								
				."<div class='form-row pb-0 pt-0 mt-0 mb-3'>"
					."<div class='col'>"
						."<label for='selled_amount_with_contract' class='font-weight-bold text-muted'>Sous contrat</label>"
						."<input required class='form-control' type='number' id='selled_amount_with_contract' name='selled_amount_with_contract[]' placeholder='en CFA' value='".$speculation['selled_amount_with_contract']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='selled_amount_without_contract' class='font-weight-bold text-muted'>Hors contrat</label>"
						."<input required class='form-control' type='number' id='selled_amount_without_contract' name='selled_amount_without_contract[]' placeholder='en CFA' value='".$speculation['selled_amount_without_contract']."'/> "      
					."</div>"
				."</div>"
				."<!-- Stock  -->"
				."<label for='' class='font-weight-bold'>Stock</label>"									
				."<div class='form-row pb-0 pt-0 mt-0 mb-3'>"
					."<div class='col'>"
						."<label for='quantity_in_stock' class='font-weight-bold text-muted'>Quantit&eacute;</label>"
						."<input required class='form-control' type='number' id='quantity_in_stock' name='quantity_in_stock[]' value='".$speculation['quantity_in_stock']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='stock_value' class='font-weight-bold text-muted'>Valeur</label>"
						."<input required class='form-control' type='number' id='stock_value' name='stock_value[]' placeholder='en CFA' value='".$speculation['stock_value']."'/>"       
					."</div>"
				."</div>"
				."<!-- Consommation  -->"
				."<label for='' class='font-weight-bold'>Consommation</label>"									
				."<div class='form-row pb-0 pt-0 mt-0 mb-3'>"
					."<div class='col'>"
						."<label for='quantity_consumed' class='font-weight-bold text-muted'>Quantit&eacute;</label>"
						."<input required class='form-control' type='number' id='quantity_consumed' name='quantity_consumed[]' value='".$speculation['quantity_consumed']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='consumed_value' class='font-weight-bold text-muted'>Valeur</label>"
						."<input required class='form-control' type='number' id='consumed_value' name='consumed_value[]' placeholder='en CFA' value='".$speculation['consumed_value']."'/>"      
					."</div>"
				."</div>"
				."<!-- Perte  -->"
				."<label for='' class='font-weight-bold'>Perte</label>"									
				."<div class='form-row pb-0 pt-0 mt-0 mb-3'>"
					."<div class='col'>"
						."<label for='quantity_lost' class='font-weight-bold text-muted'>Quantit&eacute;</label>"
						."<input required class='form-control' type='number' id='quantity_lost' name='quantity_lost[]' value='".$speculation['quantity_lost']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='lost_value' class='font-weight-bold text-muted'>Valeur</label>"
						."<input required class='form-control' type='number' id='lost_value' name='lost_value[]' placeholder='en CFA' value='".$speculation['lost_value']."'/>"       
					."</div>"
				."</div>"	
				."<!-- Autres revenues -->"
				."<label for='' class='font-weight-bold'>Autres recettes du p&eacute;rim&egrave;tre</label>"									
				."<div class='form-row pb-0 pt-0 mt-0 mb-3'>"
					."<div class='col'>"
						."<label for='other_revenues' class='font-weight-bold text-muted'>Montant</label>"
						."<input required class='form-control' type='number' id='other_revenues' name='other_revenues[]' placeholder='en CFA' value='".$speculation['other_revenues']."'/>"       
					."</div>"
					."<!--<div class='col'>"
						."<label for='other_amount_description' class='text-muted font-weight-bold'>Description</label>"
						."<input required class='form-control' type='text' id='other_revenues_description' name='other_revenues_description[]' value=''/>"       
					."</div>-->"
				."</div>"	
				."<hr class='m-4 border border-secondary bg-secondary' size=5 />"
			."</div>";
		}
		return $html_speculations;
	}
