<?php
	function reconstruct_supports($supports, $enterprise=false, $cooperative=false){
		$html_supports = "";
		foreach($supports as $support){
			$html_supports .= 
			"<div class='base'>"
				."<!-- Champ support id -->"
				."<input type='hidden' id='support_id' name='support_id[]' value='".$support['id']."'/>"     
				."<!-- Prestataire -->";
			
			if($enterprise){	
			$html_supports .=
				"<div class='form-group pb-0 pt-0 mt-0'>"
					."<label for='provider' class='font-weight-bold'>Fournisseur</label>"
					."<select class='form-control'" 
						."data-validation='non_empty_select'"
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'"
						."id='provider' name='provider[]'>"
						."<option value='-'>-</option>"
						."<option value='CAPER' ".(($support['provider'] == 'CAPER')? 'selected' : '').">CAPER</option>"
						."<option value='CCA' ".(($support['provider'] == 'CCA')? 'selected' : '').">CCA</option>"
						."<option value='WV' ".(($support['provider'] == 'WV')? 'selected' : '').">WV</option>"
						."<option value='BAOBAB-UNCDF' ".(($support['provider'] == 'BAOBAB-UNCDF')? 'selected' : '').">BAOBAB-UNCDF</option>"
						."<option value='COOPEC-RESOPP' ".(($support['provider'] == 'COOPEC-RESOPP')? 'selected' : '').">COOPEC-RESOPP</option>"
						."<option value='ANCAR' ".(($support['provider'] == 'ANCAR')? 'selected' : '').">ANCAR</option>"
						."<option value='ISRA' ".(($support['provider'] == 'ISRA')? 'selected' : '').">ISRA</option>"
						."<option value='ECLOSIO' ".(($support['provider'] == 'ECLOSIO')? 'selected' : '').">ECLOSIO</option>"
						."<option value='AUTRE' ".(($support['provider'] == 'AUTRE')? 'selected' : '').">Autre</option>"
					."</select>"    
				."</div>";
			}else{
				$html_supports .= 
				"<div class='form-group pb-0 pt-0 mt-0'>"
					."<label for='provider' class='font-weight-bold'>Fournisseur</label>"
					."<select class='form-control'" 
						."data-validation='non_empty_select'"
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'"
						."id='provider' name='provider[]'>"
						."<option value='-'>-</option>"
						."<option value='CAPER' ".(($support['provider'] == 'CAPER')? 'selected' : '').">CAPER</option>"
						."<option value='CCA' ".(($support['provider'] == 'CCA')? 'selected' : '').">CCA</option>"
						."<option value='WV' ".(($support['provider'] == 'WV')? 'selected' : '').">WV</option>"
						."<option value='BAOBAB-UNCDF' ".(($support['provider'] == 'BAOBAB-UNCDF')? 'selected' : '').">BAOBAB-UNCDF</option>"
						."<option value='COOPEC-RESOPP' ".(($support['provider'] == 'COOPEC-RESOPP')? 'selected' : '').">COOPEC-RESOPP</option>"
						."<option value='PME' ".(($support['provider'] == 'PME')? 'selected' : '').">PME</option>"
						."<option value='AUTRE' ".(($support['provider'] == 'AUTRE')? 'selected' : '').">Autre</option>"
					."</select>"    
				."</div>";				
			}
			$html_supports .= 
				"<!-- Autre Fournisseur -->"
				."<div class='form-group pb-0 pt-0 mt-0' style='display:none'>"
					."<label for='other_provider' class='font-weight-bold'>Autre fournisseur</label>"
					."<input data-validation='required' class='form-control' type='text' id='other_provider' name='other_provider[]'/>"       
				."</div>"
				."<!-- Type appui -->"
				."<div class='form-group pb-0 pt-0 mt-0'>"
					."<label for='type' class='font-weight-bold'>Type appui</label>"
					."<select class='form-control' id='type' name='type[]'"
						."multiple"
						."data-validation='non_empty_select'"
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'"
						."<option value='-'>-</option>"
						."<option value='COACHING' ".((strpos($support['type'], 'COACHING') !== false)? 'selected' : '').">Appui conseil / Coaching</option>"
						."<option value='FORMATION' ".((strpos($support['type'], 'FORMATION') !== false)? 'selected' : '').">Formation</option>"
						."<option value='MISE EN RESEAU' ".((strpos($support['type'], 'MISE EN RESEAU') !== false)? 'selected' : '').">Mise en r&eacute;seau</option>"
						."<option value='AUTRE' ".((strpos($support['type'], 'AUTRE') !== false)? 'selected' : '').">Autre</option>"
					."</select>"        
				."</div>";
			if($cooperative){
				$html_supports .= 
				"<!-- Instances Formes -->"
				."<div class='form-group pb-0 pt-0 mt-0'>"
					."<label for='trained_instances' class='font-weight-bold'>Instances Form&eacute;es</label>"
					."<select required class='form-control' id='trained_instances' name='trained_instances[]'"
						."multiple"
						."data-validation='non_empty_select'"
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'>"
						."<option value='-'>-</option>"
						."<option value='CA' ".((strpos($support['trained_instances'], 'CA') !== false)? 'selected' : '').">Conseil d'administration</option>"
						."<option value='BE' ".((strpos($support['trained_instances'], 'BE') !== false)? 'selected' : '').">Bureau ex&eacute;cutif</option>"
						."<option value='CS' ".((strpos($support['trained_instances'], 'CS') !== false)? 'selected' : '').">Conseil de surveillance</option>"
						."<option value='CD' ".((strpos($support['trained_instances'], 'CD') !== false)? 'selected' : '').">Comit&eacute; directeur</option>"
						."<option value='CT' ".((strpos($support['trained_instances'], 'CT') !== false)? 'selected' : '').">Commission technique</option>"
						."<option value='AUTRE' ".((strpos($support['trained_instances'], 'AUTRE') !== false)? 'selected' : '').">Autre</option>"
					."</select>"        
				."</div>";
			}
			$html_supports .= 	
			"<!-- Autre Appui -->"
				."<div class='form-group pb-0 pt-0 mt-0' style='display:none'>"
					."<label for='other_support' class='font-weight-bold'>Autre type d'appui</label>"
					."<input data-validation='required' class='form-control' type='text' id='other_support' name='other_support[]'/>"       
				."</div>"
				."<!-- Beneficiaires -->"
				."<label for='' class='font-weight-bold'>B&eacute;n&eacute;ficiaires</label>"									
				."<div class='form-row pb-0 pt-0 mt-0 mb-3'>"
					."<div class='col'>"
						."<label for='men_beneficiary_lt35' class='font-weight-bold text-muted'>H Jeunes</label>"
						."<input class='form-control' type='number'" 
						."data-validation='required number'" 
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'"
						."id='men_beneficiary_lt35' name='men_beneficiary_lt35[]' value='".$support['men_beneficiary_lt35']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='men_beneficiary_gt35' class='font-weight-bold text-muted'>H Adultes</label>"
						."<input class='form-control' type='number'" 
						."data-validation='required number'"
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'"
						."id='men_beneficiary_gt35' name='men_beneficiary_gt35[]' value='".$support['men_beneficiary_gt35']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='women_beneficiary_lt35' class='font-weight-bold text-muted'>F Jeunes</label>"
						."<input class='form-control' type='number'" 
						."data-validation='required number' id='women_beneficiary_lt35'" 
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'"
						."name='women_beneficiary_lt35[]' value='".$support['women_beneficiary_lt35']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='women_beneficiary_gt35' class='font-weight-bold text-muted'>F Adultes</label>"
						."<input class='form-control' type='number'" 
						."data-validation='required number'" 
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'"
						."id='women_beneficiary_gt35' name='women_beneficiary_gt35[]' value='".$support['women_beneficiary_gt35']."'/>"       
					."</div>"
				."</div>"
				."<!-- Beneficiaires MR -->"
				."<label for='' class='font-weight-bold'>B&eacute;n&eacute;ficiaires Migrants</label>"									
				."<div class='form-row pb-0 pt-0 mt-0 mb-3'>"
					."<div class='col'>"
						."<label for='mr_men_beneficiary_lt35' class='font-weight-bold text-muted'>H Jeunes</label>"
						."<input class='form-control' type='number'" 
						."data-validation='required number' id='mr_men_beneficiary_lt35'" 
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'"
						."name='mr_men_beneficiary_lt35[]' value='".$support['mr_men_beneficiary_lt35']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='mr_men_beneficiary_gt35' class='font-weight-bold text-muted'>H Adultes</label>"
						."<input class='form-control' type='number'" 
						."data-validation='required number' id='mr_men_beneficiary_gt35'" 
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'"
						."name='mr_men_beneficiary_gt35[]' value='".$support['mr_men_beneficiary_gt35']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='mr_women_beneficiary_lt35' class='font-weight-bold text-muted'>F Jeunes</label>"
						."<input class='form-control' type='number'" 
						."data-validation='required number' id='mr_women_beneficiary_lt35'" 
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'"
						."name='mr_women_beneficiary_lt35[]' value='".$support['mr_women_beneficiary_lt35']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='mr_women_beneficiary_gt35' class='font-weight-bold text-muted'>F Adultes</label>"
						."<input class='form-control' type='number'" 
						."data-validation='required number' id='mr_women_beneficiary_gt35'" 
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'"
						."name='mr_women_beneficiary_gt35[]' value='".$support['mr_women_beneficiary_gt35']."'/>"       
					."</div>"
				."</div>"	
				."<!-- Beneficiaires PVH-->"
				."<label for='' class='font-weight-bold'>B&eacute;n&eacute;ficiaires PVH</label>"									
				."<div class='form-row pb-0 pt-0 mt-0 mb-3'>"
					."<div class='col'>"
						."<label for='pvh_men_beneficiary_lt35' class='font-weight-bold text-muted'>H Jeunes</label>"
						."<input class='form-control' type='number'" 
						."data-validation='required number'" 
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'"
						."id='pvh_men_beneficiary_lt35' name='pvh_men_beneficiary_lt35[]' value='".$support['pvh_men_beneficiary_lt35']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='pvh_men_beneficiary_gt35' class='font-weight-bold text-muted'>H Adultes</label>"
						."<input class='form-control' type='number'" 
						."data-validation='required number'" 
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'"
						."id='pvh_men_beneficiary_gt35' name='pvh_men_beneficiary_gt35[]' value='".$support['pvh_men_beneficiary_gt35']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='pvh_women_beneficiary_lt35' class='font-weight-bold text-muted'>F Jeunes</label>"
						."<input class='form-control' type='number'" 
						."data-validation='required number'" 
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'"
						."id='pvh_women_beneficiary_lt35' name='pvh_women_beneficiary_lt35[]' value='".$support['pvh_women_beneficiary_lt35']."'/>"       
					."</div>"
					."<div class='col'>"
						."<label for='pvh_women_beneficiary_gt35' class='font-weight-bold text-muted'>F Adultes</label>"
						."<input class='form-control' type='number'" 
						."data-validation='required number'" 
						."data-validation-depends-on='capacity_building'" 
						."data-validation-depends-on-value='true'"
						."id='pvh_women_beneficiary_gt35' name='pvh_women_beneficiary_gt35[]' value='".$support['pvh_women_beneficiary_gt35']."'/>"       
					."</div>"
				."</div>"	
				."<hr class='m-4 border border-secondary bg-secondary' size=5 />"
			."</div>";
		}
		return $html_supports;
	}
